### ISSUE TITLE
windows and stable support

### ISSUE THREAD

**Issue by xmclark** [vertexclique/bastion#18]
Does this project aim to support stable channel and windows targets?

I was unable to build bastion on `stable-x86_64-pc-windows-gnu`. There is one unix-only package and some required nightly features.

I created a [draft PR](https://github.com/vertexclique/bastion/pull/17) that removes the unused nightly features and swaps the sigint catching for a platform solution using ctrlc crate.

I tested `build` and `test` on a few targets:
- `stable-x86_64-pc-windows-gnu`
- `nightly-x86_64-pc-windows-gnu`
- `stable-x86_64-unknown-linux-gnu`
- `nightly-x86_64-unknown-linux-gnu`

It all seems to work. Is this project interested in taking on support for stable and windows?

**Comment by vertexclique** [comment]
That's awesome, and thanks for it!
I am unsure about the support of Windows since I haven't tested on Windows.
If people want to use it on Windows, why not? Definitely!
I am seeking continuous contributors and want to move this project to an organization if people want to help me maintain.

**Comment by xmclark** [comment]
To improve windows confidence, you could add Appveyor or azure pipelines build step for PRs.

I’m happy to help with that.

**Comment by vertexclique** [comment]
Would be nice, would like to include that in.

**Comment by vertexclique** [comment]
This is resolved. Now builds are working on Windows! Thanks for it @xmclark !
